import "./globals.scss"
import Navbar from "@/components/navbar/Navbar"
import { transformLocale } from "@/components/utils/utils"
import { lazy } from "react"

const Footer = lazy(() => import("@/components/footer/Footer"))

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode,
  params: { lang: "de" | "en" }
}) {

  return (
    <html lang={`${params?.lang ?? "de"}`}>
      <body>
        <Navbar lang={transformLocale(params.lang)} />
        {children}
        <Footer lang={params?.lang}/>
      </body>
    </html>
  )
}
